/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PublicSegment { 'status' : Status, 'prompt' : string }
export interface PublicVideoSession {
  'owner' : [] | [Principal],
  'segments' : Array<PublicSegment>,
  'segmentPrompts' : Array<string>,
  'perClipDuration' : bigint,
  'originalPrompt' : string,
}
export type Status = { 'generating' : null } |
  { 'completed' : null } |
  { 'queued' : null } |
  { 'failed' : string };
export type Time = bigint;
export type VideoSessionId = bigint;
export interface VideoSessionSummary {
  'id' : VideoSessionId,
  'owner' : [] | [Principal],
  'segmentCount' : bigint,
  'createdAt' : Time,
  'originalPrompt' : string,
}
export interface _SERVICE {
  'createSession' : ActorMethod<
    [string, Array<string>, bigint],
    VideoSessionId
  >,
  'getSession' : ActorMethod<[VideoSessionId], PublicVideoSession>,
  'getUserSessions' : ActorMethod<[Principal], Array<VideoSessionSummary>>,
  'updateSegmentStatus' : ActorMethod<
    [VideoSessionId, bigint, Status],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];