/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VideoSessionId = IDL.Nat;
export const Status = IDL.Variant({
  'generating' : IDL.Null,
  'completed' : IDL.Null,
  'queued' : IDL.Null,
  'failed' : IDL.Text,
});
export const PublicSegment = IDL.Record({
  'status' : Status,
  'prompt' : IDL.Text,
});
export const PublicVideoSession = IDL.Record({
  'owner' : IDL.Opt(IDL.Principal),
  'segments' : IDL.Vec(PublicSegment),
  'segmentPrompts' : IDL.Vec(IDL.Text),
  'perClipDuration' : IDL.Nat,
  'originalPrompt' : IDL.Text,
});
export const Time = IDL.Int;
export const VideoSessionSummary = IDL.Record({
  'id' : VideoSessionId,
  'owner' : IDL.Opt(IDL.Principal),
  'segmentCount' : IDL.Nat,
  'createdAt' : Time,
  'originalPrompt' : IDL.Text,
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [VideoSessionId],
      [],
    ),
  'getSession' : IDL.Func([VideoSessionId], [PublicVideoSession], ['query']),
  'getUserSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoSessionSummary)],
      ['query'],
    ),
  'updateSegmentStatus' : IDL.Func([VideoSessionId, IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VideoSessionId = IDL.Nat;
  const Status = IDL.Variant({
    'generating' : IDL.Null,
    'completed' : IDL.Null,
    'queued' : IDL.Null,
    'failed' : IDL.Text,
  });
  const PublicSegment = IDL.Record({ 'status' : Status, 'prompt' : IDL.Text });
  const PublicVideoSession = IDL.Record({
    'owner' : IDL.Opt(IDL.Principal),
    'segments' : IDL.Vec(PublicSegment),
    'segmentPrompts' : IDL.Vec(IDL.Text),
    'perClipDuration' : IDL.Nat,
    'originalPrompt' : IDL.Text,
  });
  const Time = IDL.Int;
  const VideoSessionSummary = IDL.Record({
    'id' : VideoSessionId,
    'owner' : IDL.Opt(IDL.Principal),
    'segmentCount' : IDL.Nat,
    'createdAt' : Time,
    'originalPrompt' : IDL.Text,
  });
  
  return IDL.Service({
    'createSession' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [VideoSessionId],
        [],
      ),
    'getSession' : IDL.Func([VideoSessionId], [PublicVideoSession], ['query']),
    'getUserSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoSessionSummary)],
        ['query'],
      ),
    'updateSegmentStatus' : IDL.Func([VideoSessionId, IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };