/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PublicVideoSession {
    owner?: Principal;
    segments: Array<PublicSegment>;
    segmentPrompts: Array<string>;
    perClipDuration: bigint;
    originalPrompt: string;
}
export type Time = bigint;
export interface VideoSessionSummary {
    id: VideoSessionId;
    owner?: Principal;
    segmentCount: bigint;
    createdAt: Time;
    originalPrompt: string;
}
export type VideoSessionId = bigint;
export type Status = {
    __kind__: "generating";
    generating: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "queued";
    queued: null;
} | {
    __kind__: "failed";
    failed: string;
};
export interface PublicSegment {
    status: Status;
    prompt: string;
}
export interface backendInterface {
    createSession(originalPrompt: string, segmentPrompts: Array<string>, perClipDuration: bigint): Promise<VideoSessionId>;
    getSession(sessionId: VideoSessionId): Promise<PublicVideoSession>;
    getUserSessions(user: Principal): Promise<Array<VideoSessionSummary>>;
    updateSegmentStatus(sessionId: VideoSessionId, segmentId: bigint, newStatus: Status): Promise<void>;
}
import type { PublicSegment as _PublicSegment, PublicVideoSession as _PublicVideoSession, Status as _Status, Time as _Time, VideoSessionId as _VideoSessionId, VideoSessionSummary as _VideoSessionSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createSession(arg0: string, arg1: Array<string>, arg2: bigint): Promise<VideoSessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, arg1, arg2);
            return result;
        }
    }
    async getSession(arg0: VideoSessionId): Promise<PublicVideoSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_PublicVideoSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_PublicVideoSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSessions(arg0: Principal): Promise<Array<VideoSessionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSessions(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSessions(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSegmentStatus(arg0: VideoSessionId, arg1: bigint, arg2: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSegmentStatus(arg0, arg1, to_candid_Status_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSegmentStatus(arg0, arg1, to_candid_Status_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_PublicSegment_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicSegment): PublicSegment {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PublicVideoSession_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicVideoSession): PublicVideoSession {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_VideoSessionSummary_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoSessionSummary): VideoSessionSummary {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoSessionId;
    owner: [] | [Principal];
    segmentCount: bigint;
    createdAt: _Time;
    originalPrompt: string;
}): {
    id: VideoSessionId;
    owner?: Principal;
    segmentCount: bigint;
    createdAt: Time;
    originalPrompt: string;
} {
    return {
        id: value.id,
        owner: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.owner)),
        segmentCount: value.segmentCount,
        createdAt: value.createdAt,
        originalPrompt: value.originalPrompt
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: [] | [Principal];
    segments: Array<_PublicSegment>;
    segmentPrompts: Array<string>;
    perClipDuration: bigint;
    originalPrompt: string;
}): {
    owner?: Principal;
    segments: Array<PublicSegment>;
    segmentPrompts: Array<string>;
    perClipDuration: bigint;
    originalPrompt: string;
} {
    return {
        owner: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.owner)),
        segments: from_candid_vec_n4(_uploadFile, _downloadFile, value.segments),
        segmentPrompts: value.segmentPrompts,
        perClipDuration: value.perClipDuration,
        originalPrompt: value.originalPrompt
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    prompt: string;
}): {
    status: Status;
    prompt: string;
} {
    return {
        status: from_candid_Status_n7(_uploadFile, _downloadFile, value.status),
        prompt: value.prompt
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generating: null;
} | {
    completed: null;
} | {
    queued: null;
} | {
    failed: string;
}): {
    __kind__: "generating";
    generating: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "queued";
    queued: null;
} | {
    __kind__: "failed";
    failed: string;
} {
    return "generating" in value ? {
        __kind__: "generating",
        generating: value.generating
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "queued" in value ? {
        __kind__: "queued",
        queued: value.queued
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicSegment>): Array<PublicSegment> {
    return value.map((x)=>from_candid_PublicSegment_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoSessionSummary>): Array<VideoSessionSummary> {
    return value.map((x)=>from_candid_VideoSessionSummary_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Status_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "generating";
    generating: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "queued";
    queued: null;
} | {
    __kind__: "failed";
    failed: string;
}): {
    generating: null;
} | {
    completed: null;
} | {
    queued: null;
} | {
    failed: string;
} {
    return value.__kind__ === "generating" ? {
        generating: value.generating
    } : value.__kind__ === "completed" ? {
        completed: value.completed
    } : value.__kind__ === "queued" ? {
        queued: value.queued
    } : value.__kind__ === "failed" ? {
        failed: value.failed
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
